before:
  hooks:
    - go mod tidy
builds:
  - id: commenter
    main: ./cmd/commenter
    binary: commenter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

snapshot:
  name_template: "{{ .Tag }}-next"

archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

release:
  prerelease: auto
  github:
    owner: kathleen-french
    name: tfsec-pr-commenter-action

